name: Build manywheel docker images

on:
  push:
    branches:
      master
    paths:
      - manywheel/Dockerfile
      - 'common/*'
  pull_request:
    paths:
      - manywheel/Dockerfile
      - 'common/*'

env:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_BUILDKIT: 1
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  WITH_PUSH: ${{ github.event_name == 'push' }}

jobs:
  build-docker-cuda:
    runs-on: linux.2xlarge
    strategy:
      matrix:
        cuda_version: ["11.3"]
    env:
      GPU_ARCH_TYPE: cuda
      GPU_ARCH_VERSION: ${{ matrix.cuda_version }}
    steps:
      - name: Checkout PyTorch
        uses: actions/checkout@v2
      - name: Authenticate if WITH_PUSH
        run: |
          if [[ "${WITH_PUSH}" == true ]]; then
            echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_ID}" --password--stdin
          fi
      - name: Build Docker Image
        run: |
          manywheel/build_docker.sh
  build-docker-rocm:
    runs-on: linux.2xlarge
    strategy:
      matrix:
        rocm_version: ["4.0.1", "4.1", "4.2"]
    env:
      GPU_ARCH_TYPE: rocm
      GPU_ARCH_VERSION: ${{ matrix.rocm_version }}
    steps:
      - name: Checkout PyTorch
        uses: actions/checkout@v2
      - name: Authenticate if WITH_PUSH
        run: |
          if [[ "${WITH_PUSH}" == true ]]; then
            echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_ID}" --password--stdin
          fi
      - name: Build Docker Image
        run: |
          manywheel/build_docker.sh
  build-docker-cpu:
    runs-on: linux.2xlarge
    steps:
      - name: Checkout PyTorch
        uses: actions/checkout@v2
      - name: Authenticate if WITH_PUSH
        run: |
          if [[ "${WITH_PUSH}" == true ]]; then
            echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_ID}" --password--stdin
          fi
      - name: Build Docker Image
        run: |
          manywheel/build_docker.sh
